webpro-exercise-init_week6/attendance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classes.urls')),
    path('reports/', include('reports.urls')),
    path('management/', include('management.urls')),
]

webpro-exercise-init_week6/classes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:class_id>/', views.detail, name='class_detail'),
    path('check-in/<int:class_id>/', views.check_in, name='class_check_in'),
]

webpro-exercise-init_week6/management/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('student/list/', views.student_list, name='student_list'),
    path('student/add/', views.student_add, name='student_add'),
    path('student/delete/<int:student_id>/', views.student_delete, name='student_delete'),
    path('class/list/', views.class_list, name='class_list'),
    path('class/add/', views.class_add, name='class_add'),
    path('class/delete/<int:class_id>/', views.class_delete, name='class_delete'),
]

webpro-exercise-init_week6/reports/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('search/', views.search, name='class_search'),
]

webpro-exercise-init_week6/classes/models.py
from django.db import models

from management.models import ClassRoom, Student

class StudentAttendance(models.Model):
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    attend = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now=True)

webpro-exercise-init_week6/management/models.py
from django.db import models


# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=10)

class Course(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    semester = models.CharField(max_length=1) # ภาคเรียน
    academic_year = models.CharField(max_length=4) # ปีการศึกษา


class Student(models.Model):
    student_code = models.CharField(max_length=10)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=100)
    year = models.SmallIntegerField() # ชั้นปี


class ClassRoom(models.Model):
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    section = models.SmallIntegerField()
    WEEKDAYS = (
        ('M', 'Monday'),
        ('T', 'Tuesday'),
        ('W', 'Wednesday'),
        ('TH', 'Thursday'),
        ('F', 'Friday'),
        ('S', 'Saturday'),
        ('Su', 'Sunday'),
    )
    weekday = models.CharField(max_length=2, choices=WEEKDAYS)
    start_time = models.TimeField()
    end_time = models.TimeField()
    room = models.ForeignKey(Room, on_delete=models.PROTECT)
    student_amount = models.IntegerField(default=0) # จำนวน นศ. ที่ลงทะเบียนทั้งหมด
    students = models.ManyToManyField(
        Student, 
        through='classes.StudentAttendance'
    )

webpro-exercise-init_week6/reports/models.py
from django.db import models

# Create your models here.

webpro-exercise-init_week6/classes/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from management.models import Student

# Create your views here.
def index(request):
    """
        Index page - หน้าจอรายการวิชาที่มีการสอนทั้งหมด
    """
    search_txt = request.GET.get('inputSearch')
    print(search_txt)
    return render(request, 'classes/index.html', context={
        'search_txt': search_txt
    })

def detail(request, class_id):
    """
        Class detail page – เมื่อกด link จากหน้า Index page มาจะได้หน้าจอแสดงรายละเอียดของแต่ละวิชา 
        (วิชานี้สอนอะไร, มีจำนวนนักเรียนกี่คน, มีคนมาเรียน และขาดกี่คน)
    """
    return render(request, 'classes/detail.html', context={})

def check_in(request, class_id):
    """
        Check-in page - เมื่อกดปุ่ม Check in ในหน้า Course detail page จะทำการบันทึกกว่าเช็คชื่อเข้าเรียน 
        (ให้ใช้ student ที่มี id = 1 เสมอทุกครั้งที่กด Check in เนื่องจากเรายังไม่ได้เรียนเกี่ยวกับการจัดการ login logout และ user ของ Django)
        โดยถ้ากดปุ่ม Check in ซ้ำจะเป็นการไปบันทึกเวลาใหม่ในรายการเดิม
    """
    student = Student.objects.get(pk=1)

    return redirect(to='class_detail', class_id=class_id)

webpro-exercise-init_week6/management/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from management.models import ClassRoom



# Create your views here.
def student_list(request):
    return HttpResponse('List Student Page.')

def student_add(request):
    return HttpResponse('Add Student Page.')

def student_delete(request, student_id):
    return HttpResponse('Delete Student Page.')

def class_list(request):
    """
        แสดงข้อมูล classroom ทั้งหมดในระบบ
    """
    course = ClassRoom.objects.all()
    context = {'classroom': course}
    # context = dict()
    # context['classroom'] = course
    return render(request, 'management/class_list.html', context)

def class_add(request):
    """
        เพิ่มข้อมูล classroom ใหม่เข้าสู่ฐานข้อมูล
    """
    
    return render(request, 'management/class_add.html')

def class_delete(request, class_id):
    """
        ลบข้อมูล classroom โดยลบข้อมูลที่มี id = class_id
    """
    ClassRoom.objects.filter(id=class_id).delete()
    return redirect(to='class_list')

webpro-exercise-init_week6/reports/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def dashboard(request):
    return HttpResponse('Dashboard Page.')

def search(request):
    return HttpResponse('Attendance Search Page.')

webpro-exercise-init_week6/classes/templates/classes/detail.html
{% extends "base.html" %}
{% block content %}
<style>
    .btn{
        margin-right: 1em;
    }
</style>

<h1>Course Name: {{ sel_course.name }} ({{ sel_course.code }})</h1>
<p><b>Course Description :</b> {{ sel_course.description|truncatechars:50 }}</p>
<p><b>Section :</b> {{ sel_class.section }}</p>
<p><b>Time :</b> {{ sel_class.time|default_if_none:'N/A' }}</p>
<p><b>Room :</b> {{ sel_class.room|default_if_none:'N/A' }}</p>
<p><b>Current Date/Time:</b> {% now "jS F Y H:i" %}</p>
<a href="{% url 'class_check_in' class_id=sel_class.id %}">
    <div class="btn btn-primary">Check in</div>
</a>
<hr>
<div class="row">
    <span class="btn btn-warning">
        Total Students: <span class="badge badge-light">{{ sel_class.student_amount }}</span>
    </span>
    <span class="btn btn-success">
        Attend: <span class="badge badge-light">{{ sel_attend.attend }}</span>
    </span>
    <span class="btn btn-danger">
        Absent: <span class="badge badge-light">{{ sel_attend.absent }}</span>
    </span>
</div>
{% endblock content %}

webpro-exercise-init_week6/classes/templates/classes/index.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1>Welcome to Class Attendance System</h1>
        <br/><br/>
        <form class="form-inline" method="GET" action="{% url 'index' %}">
            <div class="form-group">
                <label for="inputSearch">ค้นหาชื่อรายวิชา:</label>
                <input type="text" class="form-control ml-3" id="inputSearch" 
                    name="inputSearch" placeholder="Search" value="{{search_txt}}">
            </div>
            <button type="submit" class="btn btn-primary ml-3">Submit</button>
        </form>
        <br/><br/>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">รหัสวิชา</th>
                    <th scope="col">ชื่อรายวิชา</th>
                    <th scope="col">Section</th>
                    <th scope="col">วัน</th>
                    <th scope="col">เวลา</th>
                    <th scope="col">ห้อง</th>
                    <th scope="col">จำนวนนักเรียนที่ลงทะเบียน</th>
                    <th scope="col">ลบข้อมูล</th>
                </tr>
            </thead>
            <tbody>
                {% for cl in classes %}
                <tr>
                    <td>{{ cl.get_weekday_display }} @ {{ cl.time }}</td>
                    <td>{{ cl.course.name }} ({{ cl.course.code }})</td>
                    <td>{{ cl.section }}</td>
                    <td>{{ cl.room }}</td>
                    <td>{{ cl.student_amount }}</td>
                    <td>
                        <a href="{% url 'class_detail' class_id=cl.id %}">
                            <div class="btn btn-warning" id="{{cl.id}}">View detail</div>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block footer %}
    Footer of index page!!!
{% endblock %}

webpro-exercise-init_week6/management/templates/management/class_list.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h1>Welcome to Class Attendance System</h1>
        <br/><br/>
        <form class="form-inline" method="GET" action="{% url 'index' %}">
            <div class="form-group">
                <label for="inputSearch">ค้นหาชื่อรายวิชา:</label>
                <input type="text" class="form-control ml-3" id="inputSearch" 
                    name="inputSearch" placeholder="Search" value="{{search_txt}}">
            </div>
            <button type="submit" class="btn btn-primary ml-3">Submit</button>
        </form>
        <br/><br/>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">รหัสวิชา</th>
                    <th scope="col">ชื่อรายวิชา</th>
                    <th scope="col">Section</th>
                    <th scope="col">วัน</th>
                    <th scope="col">เวลา</th>
                    <th scope="col">ห้อง</th>
                    <th scope="col">จำนวนนักเรียนที่ลงทะเบียน</th>
                    <th scope="col">ลบข้อมูล</th>
                </tr>
            </thead>
            <tbody>
                {% for cl in classroom%}
                <tr>
                    <td> {{ cl.course.id }}</td>
                    <td> {{ cl.course.name }}</td>
                    <td> {{ cl.section }}</td>
                    <td> {{ cl.get_weekday_display }}</td>
                    <td> {{ cl.start_time }} - {{ cl.end_time }}</td>
                    <td> {{ cl.room_id }}</td>
                    <td> {{ cl.student_amount }}</td>
                    <td><a href="/management/class/delete/{{ cl.id }}">ลบข้อมูล</a></td>
                </tr>
                {% endfor %}
                {% comment %} {% for cl in classes %}
                <tr>
                    <td>{{ cl.weekday }} @ {{ cl.time }}</td>
                    <td>{{ cl.course.name }} ({{ cl.course.code }})</td>
                    <td>{{ cl.section }}</td>
                    <td>{{ cl.room }}</td>
                    <td>{{ cl.student_amount }}</td>
                    <td>
                        <a href="{% url 'class_detail' class_id=cl.id %}">
                            <div class="btn btn-warning" id="{{cl.id}}">View detail</div>
                        </a>
                    </td>
                </tr>
                {% endfor %} {% endcomment %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block footer %}
    Footer of index page!!!
{% endblock %}

webpro-exercise-init_week6/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Base</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css'%}">

    <style>
    header[role="banner"] {
        #logo-main {
            display: block;
            margin: 20px auto;
        }
        }

        #navbar-primary.navbar-default {
        background: transparent;
        border: none;
        .navbar-nav { 
            width: 100%;
            text-align: center;
            > li {
            display: inline-block;
            float: none;
            > a {
                padding-left: 30px;
                padding-right: 30px;
                }
            }
        }
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">LOGO HERE</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">รายชื่อวิชาสอน</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">รายงาน</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">จัดการข้อมูล</a>
                </li>
            </ul>
        </div>
    </nav>
    <br>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>